### ISSUE TITLE
Bug: duplicate observations

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/garnet#147] opened 2015-10-22 19:24 UTC
Reproduce: create an observation

Example: http://garnet.wdidc.org/groups/ga_wdi_dc_7/users/jotalp

**Comment by mattscilipoti** [comment] 2015-10-22 19:24
First one had issues saving (long spinner).  Second one seemed fine.  Both were duplicated.

**Comment by RobertAKARobin** [comment] 2015-10-22 19:26
Duplicate of https://github.com/ga-dc/garnet/issues/108

**Closed by RobertAKARobin** 2015-10-22 19:26 UTC
Labels: bug
