### ISSUE TITLE
mass event creation time zone offset

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#636] opened 2016-11-07 14:14 UTC
events this morning were set to start at 8am instead of 9

https://github.com/ga-dc/garnet/blob/4b6f03fae03e82f681b46381a417ad5b13d302bc/app/models/cohort.rb#L68-L90

https://gist.github.com/andytcox/ab26f58b5fc506676b04

**Comment by BritneyJo** [comment] 2016-11-10 15:17
Is this going to be looked at anytime soon? Not sure if issues are being handled or if we should just be correcting our students attendance since the time change? Thank you!

**Comment by andrewsunglaekim** [comment] 2016-11-12 04:59
we haven't had a chance to fix this yet, but we're in project week next week, top priority!

**Comment by BritneyJo** [comment] 2016-11-12 05:21
Fantastic news!! Thank you!

- Britney Jo Ludkowski

**Comment by andrewsunglaekim** [comment] 2016-11-12 22:38
nice @nolds9 ! can we close this? or is it a temp fix .. spose i could look at the commit

**Comment by BritneyJo** [comment] 2016-11-14 17:08
Everyone still got marked Tardy today - does this need to be merged?

**Comment by nolds9** [comment] 2016-11-14 17:14
We still need to do some testing to make sure the bug is fixed, but note that this patch will **not** retroactively fix events that were affected, this only solves future uses for the "Auto Event Generation" feature. 

Right now, I believe you will have to manually the event's time in order to make sure students will not be tardy

**Comment by BritneyJo** [comment] 2016-11-14 17:15
When trying to manually change the event's time, this error occurs:

<img width="1207" alt="screen shot 2016-11-14 at 11 15 11 am" src="https://cloud.githubusercontent.com/assets/4397530/20274838/affd6d10-aa5b-11e6-9325-113cf5dabae4.png">

**Comment by jshawl** [comment] 2016-11-14 17:22
@nolds9 may i have access to papertrail?

**Comment by nolds9** [comment] 2016-11-14 17:32
sure @jshawl what email should I use?

**Comment by jshawl** [comment] 2016-11-14 17:33
jesseshawl@gmail.com please! also maybe @BritneyJo too?

**Comment by nolds9** [comment] 2016-11-14 17:38
@BritneyJo according to the server logs, you are getting that error because that event does not exist. Do you mind sending the steps you took to reproduce?

**Comment by andrewsunglaekim** [comment] 2016-11-14 17:40
also @BritneyJo  you won't like this but, as a manual work around go to that events show page and update student tardies.

**Comment by nolds9** [comment] 2016-11-14 17:43
looks like we have a different bug triggered by the update of an event...

![image](https://cloud.githubusercontent.com/assets/10698044/20275824/ee41d168-aa67-11e6-9706-43a71e0039a1.png)

**Comment by BritneyJo** [comment] 2016-11-14 17:50
We have been going to the individual date (event) and updating tardies to present, but a new cohort just started today so we'd like to get it sorted otherwise we'll probably just discontinue use for attendance :/

As for the above error, we have events created from the beginning of the cohort that were autogenerated based on the cohort's dates. I clicked a date under Attendance and tried to update the time from 9am - 8am. When saving, the error I posted above shows up.

I also tried to delete the date entirely, but when it takes me back to the main page, I see it is still in the list. So I clicked on it again, and now I get a 404. So the event must have been deleted but it's still showing in our overall list of Attendance. 

<img width="1202" alt="screen shot 2016-11-14 at 11 47 44 am" src="https://cloud.githubusercontent.com/assets/4397530/20276060/575f98fe-aa60-11e6-979a-c1bd180f48ce.png">

Thank you guys for even looking at this! I'd hate to lose the attendance part of Garnet - it's been such a wonderful addition to our teaching here in Austin!

**Comment by jshawl** [comment] 2016-11-14 19:28
oh dang it could be caching as well.

Just cleared the cache @BritneyJo still having that issue?

**Comment by BritneyJo** [comment] 2016-11-14 19:32
The two previous date events I deleted are now gone, but when I delete another, I'm still getting the 404 even after a hard refresh.

**Comment by jshawl** [comment] 2016-11-14 19:38
ah ok this is caching on the main cohort show page I believe - https://github.com/ga-dc/garnet/blob/4b6f03fae03e82f681b46381a417ad5b13d302bc/app/views/cohorts/show.html.erb#L24

worst case scenario - you can delete all the ones you want and then ask me to clear the cache

**Closed** 2016-11-15 17:17 UTC
